"""empty message

Revision ID: a0acff4f976
Revises: 2956c7423d73
Create Date: 2014-03-14 01:18:57.787793

"""

# revision identifiers, used by Alembic.
revision = 'a0acff4f976'
down_revision = '2956c7423d73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
