"""empty message

Revision ID: 59764b2fd53
Revises: None
Create Date: 2014-03-12 00:56:08.285016

"""

# revision identifiers, used by Alembic.
revision = '59764b2fd53'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
